version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - '8888:80'
    depends_on:
      - php
    volumes:
      - /var/www/html:/usr/share/nginx/html
  php:
    build: ./php
    depends_on:
      - mysql
    volumes:
      - /var/www/html:/var/www/html
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
